#!/usr/bin/python3
import subprocess

def run_cmd(cmd):
    subprocess.call(cmd, shell=True)

vmrun = r'/cygdrive/c/Program\ Files\ \(x86\)/VMware/VMware\ VIX/vmrun.exe'

linux_mint_vmx = r'"C:\\Users\\rodri\\Documents\\Virtual Machines\\LinuxMint\\LinuxMint.vmx"'

cmd = f"{vmrun} getGuestIPAddress {linux_mint_vmx}"

run_cmd(cmd)
