#!/usr/bin/python3
import requests
import socket

hostname = socket.gethostname()
ip = socket.gethostbyname(hostname)
url = "http://rudysbvm:5333/?hostname={}&ip={}".format(hostname, ip)

parsed=requests.get(url).text
print(parsed)

